package parser;

import java.util.HashMap;
import java.util.Map;

public class GenreMapping {
    public static final Map<String, String> genreMapping = new HashMap<>();

    static {
        genreMapping.put("Muscl", "Musical");
        genreMapping.put("Musc", "Musical");
        genreMapping.put("musc", "Musical");
        genreMapping.put("Muusc", "Musical");
        genreMapping.put("stage musical", "Musical");
        genreMapping.put("Avant Garde", "Avant Garde");
        genreMapping.put("AvGa", "Avant Garde");
        genreMapping.put("ScFi", "Sci-Fi");
        genreMapping.put("Dram", "Drama");
        genreMapping.put("dram", "Drama");
        genreMapping.put("Dram>", "Drama");
        genreMapping.put("Dramd", "Drama");
        genreMapping.put("Dram.Actn", "Drama");
        genreMapping.put("UnDr", "Drama");
        genreMapping.put("Camp", "Drama");
        genreMapping.put("Bio", "Biography");
        genreMapping.put("BioPP", "Biography");
        genreMapping.put("Comd", "Comedy");
        genreMapping.put("comd", "Comedy");
        genreMapping.put("Comdx", "Comedy");
        genreMapping.put("RFP; H*", "Comedy");
        genreMapping.put("Scat", "Comedy");
        genreMapping.put("Actn", "Action");
        genreMapping.put("actn", "Action");
        genreMapping.put("Act", "Action");
        genreMapping.put("Axtn", "Action");
        genreMapping.put("Disa", "Action");
        genreMapping.put("Adct", "Adventure");
        genreMapping.put("RomtAdvt", "Adventure");
        genreMapping.put("Sctn", "Action");
        genreMapping.put("Romtx", "Romance");
        genreMapping.put("Romt", "Romance");
        genreMapping.put("romt", "Romance");
        genreMapping.put("Ront", "Romance");
        genreMapping.put("Romt. Comd", "Romance");
        genreMapping.put("Romt Comd", "Romance");
        genreMapping.put("Romt Fant", "Romance");
        genreMapping.put("Romt Actn", "Romance");
        genreMapping.put("ram", "Romance");
        genreMapping.put("Romt Dram", "Romance");
        genreMapping.put("H", "Romance");
        genreMapping.put("Fant", "Fantasy");
        genreMapping.put("Viol", "Gore");
        genreMapping.put("Horr", "Horror");
        genreMapping.put("Susp", "Horror");
        genreMapping.put("susp", "Horror");
        genreMapping.put("Natu", "Horror");
        genreMapping.put("Dicu", "Documentary");
        genreMapping.put("Docu", "Documentary");
        genreMapping.put("Ducu", "Documentary");
        genreMapping.put("S.F.", "Sci-Fi");
        genreMapping.put("SciF", "Sci-Fi");
        genreMapping.put("SxFi", "Sci-Fi");
        genreMapping.put("BioG", "Biography");
        genreMapping.put("BioB", "Biography");
        genreMapping.put("BioP", "Biography");
        genreMapping.put("Biop", "Biography");
        genreMapping.put("H0", "Horror");
        genreMapping.put("Hor", "Horror");
        genreMapping.put("Weird", "Fantasy");
        genreMapping.put("Myst", "Mystery");
        genreMapping.put("Mystp", "Mystery");
        genreMapping.put("Hist", "History");
        genreMapping.put("Histp", "History");
        genreMapping.put("H*", "Horror");
        genreMapping.put("H**", "Horror");
        genreMapping.put("Psych Dram", "Drama");
        genreMapping.put("Psyc", "Drama");
        genreMapping.put("Psych", "Drama");
        genreMapping.put("Ctcxx", "Comedy");
        genreMapping.put("Cart", "Animation");
        genreMapping.put("Muscl", "Musical");
        genreMapping.put("Epic", "Action");
        genreMapping.put("Weird", "Fantasy");
        genreMapping.put("Fantasy", "Fantasy");
        genreMapping.put("Advt", "Adventure");
        genreMapping.put("Faml", "Family");
        genreMapping.put("Cult", "Biography");
        genreMapping.put("Sati", "Comedy");
        genreMapping.put("TV", "TV Show");
        genreMapping.put("Noir", "Film Noir");
        genreMapping.put("noir", "Film Noir");
        genreMapping.put("Ctxx", "Film Noir");
        genreMapping.put("Comd Noir", "Film Noir");
        genreMapping.put("Duco", "Film Noir");
        genreMapping.put("Noir Comd Romt", "Film Noir");
        genreMapping.put("Noir Comd", "Film Noir");
        genreMapping.put("Allegory", "Fantasy");
        genreMapping.put("Dist", "Thriller");
        genreMapping.put("CnR", "Crime");
        genreMapping.put("CnRb", "Crime");
        genreMapping.put("CnRbb", "Crime");
        genreMapping.put("CA", "Crime");
        genreMapping.put("Crim", "Crime");
        genreMapping.put("Ctxxx", "Crime");
        genreMapping.put("CmR", "Crime");
        genreMapping.put("Cond", "Drama");
        genreMapping.put("CnRb", "Crime");
        genreMapping.put("Dicu", "Documentary");
        genreMapping.put("Dram Docu", "Drama");
        genreMapping.put("Docu Dram", "Drama");
        genreMapping.put("FantH*", "Fantasy");
        genreMapping.put("Horr", "Horror");
        genreMapping.put("SxFi", "Sci-Fi");
        genreMapping.put("Scfi", "Sci-Fi");
        genreMapping.put("West1", "Western");
        genreMapping.put("West", "Western");
        genreMapping.put("Comd West", "Western");
        genreMapping.put("S.F.", "Sci-Fi");
        genreMapping.put("Docu", "Documentary");
        genreMapping.put("Comd", "Comedy");
        genreMapping.put("FantH*", "Fantasy");
        genreMapping.put("Dist", "Thriller");
        genreMapping.put("Sctn", "Action");
        genreMapping.put("Cond", "Drama");
        genreMapping.put("BioPx", "Biography");
        genreMapping.put("Surl", "Fantasy");
        genreMapping.put("Surr", "Fantasy");
        genreMapping.put("Expm", "Fantasy");
        genreMapping.put("Surreal", "Fantasy");
        genreMapping.put("surreal", "Fantasy");
        genreMapping.put("Fantasy", "Fantasy");
        genreMapping.put("Fant", "Fantasy");
        genreMapping.put("fant", "Fantasy");
        genreMapping.put("DRam", "Drama");
        genreMapping.put("Dram", "Drama");
        genreMapping.put("Dram>", "Drama");
        genreMapping.put("DraM", "Drama");
        genreMapping.put("DRAM", "Drama");
        genreMapping.put("Dramn", "Drama");
        genreMapping.put("Draam", "Drama");
        genreMapping.put("Actn", "Action");
        genreMapping.put("Adctx", "Adventure");
        genreMapping.put("Homo", "Adventure");
        genreMapping.put("Dram", "Drama");
        genreMapping.put("BiopP", "Biography");
        genreMapping.put("BioP", "Biography");
        genreMapping.put("BioB", "Biography");
        genreMapping.put("BioPx", "Biography");
        genreMapping.put("Biop", "Biography");
        genreMapping.put("Sati", "Comedy");
        genreMapping.put("TV", "Television");
        genreMapping.put("TV Show", "Television");
        genreMapping.put("TVmini", "Television");
        genreMapping.put("porn", "Erotica");
        genreMapping.put("Porb", "Erotica");
        genreMapping.put("Erotica", "Erotica");
        genreMapping.put("Erotica", "Adult");
        genreMapping.put("Duco", "Opera");
        genreMapping.put("sports", "Sport");
        genreMapping.put("txx", "Silent");
        genreMapping.put("verite", "Experimental");
        genreMapping.put("Art Video", "Experimental");
        genreMapping.put("anti-Dram", "Drama");
    }
}
